name: wardrobe_plugin_json
main: baumkm.wardrobe.main.Main
author: BaumKM
version: 1.0.0
description: basic plugin
api-version: 1.17
commands:
  wardrobe:
    description: opens your wardrobe
    usage:  ยง6 use /wardrobe
    aliases: [w]
